package main

import (
	docs "UacademyGo/Article/docs" // docs is generated by Swag CLI, you have to import it.
	"UacademyGo/Article/handlers"
	"UacademyGo/Article/models"
	"UacademyGo/Article/storage"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// * @contact.name   API Article
// * @contact.url    http://john.doe.com
// * @contact.email  john.doe@swagger.io
// * @license.name  Apache 2.0
// * @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

func main() {
	// programmatically set swagger info
	docs.SwaggerInfo.Title = "Swagger Example API"
	docs.SwaggerInfo.Description = "This is a sample server Petstore server."
	docs.SwaggerInfo.Version = "2.0"

	err := storage.AddAuthor("52c9c9bd-2e68-401f-8ade-31dc7e7d6eea", models.CreateModelAuthor{
		Firstname: "John",
		Lastname: "Doe",
	})
	if err != nil {
		panic(err)
	}

	err = storage.AddNewArticle("32f0ef03-3907-46be-af9f-248d4e65a2a5", models.CreateModelArticle{
		Content: models.Content{
			Title: "Lorem",
			Body: "This is my Lorem pages",
		},
		AuthorID: "52c9c9bd-2e68-401f-8ade-31dc7e7d6eea",
	})
	if err != nil {
		panic(err)
	}

	r := gin.Default()

	v1 := r.Group("/v1")
	{
		v1.POST("/article", handlers.CreateArticle)
		v1.GET("/article/:id", handlers.GetArticleById)
		v1.GET("/article", handlers.GetArticleList)
		v1.PUT("/article", handlers.UpdateArticle)
		v1.DELETE("/article/:id", handlers.DeleteArticle)

		v1.GET("/ping", handlers.Pong) //*testing example the localhost

		v1.POST("author", handlers.CreateAuthor)
		v1.GET("/author/:id", handlers.GetAuthorById)
		v1.GET("/author", handlers.GetAuthorList)
		v1.PUT("/author", handlers.UpdateAuthor)
		v1.DELETE("/author/:id", handlers.DeleteAuthor)
	}

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.Run(":8000")
}
